### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mforets**
(i dont understand what does "experimental" communicate)

### CODE REVIEW

**Comment by mforets** [comment]
... If the original idea was to warn potential industrial or academic use cases that this software is still at an early stage of development, it can be said more explicitly (**although the < 1.x version somehow communicates that**).  Eg. like so:

> This software is currently under development and may contain bugs or incomplete features. It is intended for testing and educational purposes only. Do not use this software for any critical applications or in the design and construction of actual buildings. The developers assume no responsibility for any consequences resulting from the use of this software in real-world applications.

**Comment by mvanzulli** [comment]
The original idea was to add a disclaimer that this is not the actual main package planned in the roadmap of ONSAS to migrate all the features of `ONSAS.m` and development for professional applications. Given that, I'm not against removing adding the following sentence into the `REAMDE.md`:  
```
This software is currently under development and may contain bugs or incomplete features. It is intended for testing and educational purposes only. 
```
and remove the (experimental) from the name.

**Comment by jorgepz** [comment]
Hi! As Mauricio says the idea was to add an explicit disclaimer. Although this could be clear in the version for software experts, an explicit disclaimer is needed to lower expectations and preparing users for not-fully-developed features.

I agree with Mauricio's text proposal.

**Review by mvanzulli — COMMENTED** [review]
Thanks @jorgepz for the feedback. Feel free @mforets to add the sentence

**Comment by mforets** [comment]
i made some edits, shall we merge now?

**Comment by mvanzulli** [comment]
> i made some edits, shall we merge now?

Yes, thanks for the changes 👌🏼

**Pull request merged**
