### PR TITLE
Some renames

### PR DESCRIPTION
**Pull request by mforets**
I think we should remove or reduce the methods with leading underscore; especially in the case when they are exported from the module.

### CODE REVIEW

**Comment by mforets** [comment]
Each individual commit does a different rename.

**Review by mvanzulli — APPROVED** [review]
Definitely, in the future we would have to revise which methods are exported by the API since `assemble` seems to be in an internal method that the user in general might not use.

**Comment by mforets** [comment]
I think it's fair enough to think of each constituent module of ONSAS "first class" in the sense that whatever is exported should also be re-exported in ONSAS proper.

**Comment by mvanzulli** [comment]
> I think it's fair enough to think of each constituent module of ONSAS "first class" in the sense that whatever is exported should also be re-exported in ONSAS proper.

Agree, will add this into an issue

**Pull request merged**
